name: 'Reindex'

on:
  release:
    types: [prereleased,released]

jobs:
  reindex:
    name: 'Reindex updates'
    runs-on: [self-hosted,FlipperZeroShell]
    steps:
      - name: Trigger reindex
        run: |
          curl --fail -L -H "Token: ${{ secrets.INDEXER_TOKEN }}" \
              "${{ secrets.INDEXER_URL }}"/firmware/reindex
